version: '3.8'

services:
  app:
    build: .
    container_name: janusia_app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
